name: Text prepositions fixer

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'
      - '**/*.html'

jobs:
  replace_spaces:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Run script
        run: python assets/text-prepositions-fixer.py

      - name: Commit changes
        run: |
          git config --local user.email "github-actions"
          git config --local user.name "github-actions@github.com"
          git add .
          git commit -m "Add non-breaking spaces" || echo "No changes to commit"
          git push
